name: export-and-branch
on:
  workflow_dispatch:
    inputs:
      solution_name:
        description: 'Name of the solution to work on from Power Platform'
        required: true
        default: Prioritz
      solution_exported_folder:
        description: 'Folder name for staging the exported solution *do not change*'
        required: true
        default: out/exported/
      solution_folder:
        description: 'Staging the unpacked solution folder before check-in *do not change*'
        required: true
        default: out/solutions/
      solution_target_folder: 
        description: 'Folder name to be created and checked in *do not change*'
        required: true
        default: solutions/

jobs:
  export-from-dev:
    runs-on: windows-latest
    steps:
      # Cache dependencies
      - name: Cache Power Platform Actions
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-microsoft-powerplatform-actions-${{ github.sha }}

      # Checkout repository with extended timeout
      - uses: actions/checkout@v2
        with:
          lfs: true
          fetch-depth: 0
          timeout-minutes: 10

      # Export unmanaged solution
      - name: Export unmanaged solution
        uses: microsoft/powerplatform-actions/export-solution@v0.4.0
        with:
          environment-url: ${{ secrets.PowerPlatformDevUrl }}
          app-id: ${{ secrets.PowerPlatformAppID }}
          client-secret: ${{ secrets.PowerPlatformClientSecret }}
          tenant-id: ${{ secrets.PowerPlatformTenantID }}
          solution-name: ${{ github.event.inputs.solution_name }}
          solution-output-file: ${{ github.event.inputs.solution_exported_folder }}/{{ github.event.inputs.solution_name }}.zip

      # Export managed solution
      - name: Export managed solution
        uses: microsoft/powerplatform-actions/export-solution@v0.4.0
        with:
          environment-url: ${{ secrets.PowerPlatformDevUrl }}
          app-id: ${{ secrets.PowerPlatformAppID }}
          client-secret: ${{ secrets.PowerPlatformClientSecret }}
          tenant-id: ${{ secrets.PowerPlatformTenantID }}
          solution-name: ${{ github.event.inputs.solution_name }}
          solution-output-file: ${{ github.event.inputs.solution_exported_folder }}/{{ github.event.inputs.solution_name }}_managed.zip
          managed: true

      # Unpack the solution
      - name: Unpack solution
        uses: microsoft/powerplatform-actions/unpack-solution@v0.4.0
        with:
          solution-file: ${{ github.event.inputs.solution_exported_folder }}/{{ github.event.inputs.solution_name }}.zip
          solution-folder: ${{ github.event.inputs.solution_folder }}/{{ github.event.inputs.solution_name }}
          solution-type: 'Both'

      # Branch the solution and prepare for Pull Request
      - name: Branch solution and prepare for Pull Request
        uses: microsoft/powerplatform-actions/branch-solution@v0.4.0
        with:
          solution-folder: ${{ github.event.inputs.solution_folder }}/{{ github.event.inputs.solution_name }}
          solution-target-folder: ${{ github.event.inputs.solution_target_folder }}/{{ github.event.inputs.solution_name }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          allow-empty-commit: true
